export const STOCKS = [
  { symbol: "AAPL", name: "Apple", type: "stock" },
  { symbol: "MSFT", name: "Microsoft", type: "stock" },
  { symbol: "GOOGL", name: "Alphabet Class A", type: "stock" },
  { symbol: "GOOG", name: "Alphabet Class C", type: "stock" },
  { symbol: "AMZN", name: "Amazon", type: "stock" },
  { symbol: "META", name: "Meta Platforms", type: "stock" },
  { symbol: "NVDA", name: "NVIDIA", type: "stock" },
  { symbol: "TSLA", name: "Tesla", type: "stock" },
  { symbol: "ADBE", name: "Adobe", type: "stock" },
  { symbol: "CRM", name: "Salesforce", type: "stock" },
  { symbol: "INTC", name: "Intel", type: "stock" },
  { symbol: "CSCO", name: "Cisco", type: "stock" },
  { symbol: "ORCL", name: "Oracle", type: "stock" },
  { symbol: "AMD", name: "Advanced Micro Devices", type: "stock" },
  { symbol: "SNOW", name: "Snowflake", type: "stock" },
  { symbol: "UBER", name: "Uber Technologies", type: "stock" },
  { symbol: "ZM", name: "Zoom Video Communications", type: "stock" },
  { symbol: "ROKU", name: "Roku", type: "stock" },
  { symbol: "PLTR", name: "Palantir Technologies", type: "stock" },
  { symbol: "DOCU", name: "DocuSign", type: "stock" },
  { symbol: "NET", name: "Cloudflare", type: "stock" },
  { symbol: "TWLO", name: "Twilio", type: "stock" },
  { symbol: "DDOG", name: "Datadog", type: "stock" },
  { symbol: "JPM", name: "JP Morgan Chase", type: "stock" },
  { symbol: "WFC", name: "Wells Fargo", type: "stock" },
  { symbol: "V", name: "Visa", type: "stock" },
  { symbol: "MA", name: "Mastercard", type: "stock" },
  { symbol: "WMT", name: "Walmart", type: "stock" },
  { symbol: "NKE", name: "Nike", type: "stock" },
  { symbol: "MCD", name: "McDonald's", type: "stock" },
  { symbol: "SBUX", name: "Starbucks", type: "stock" },
  { symbol: "COIN", name: "Coinbase Global", type: "stock" },
  { symbol: "CRWD", name: "CrowdStrike", type: "stock" },
  { symbol: "ZS", name: "Zscaler", type: "stock" },
  { symbol: "OKTA", name: "Okta", type: "stock" },
  { symbol: "SNAP", name: "Snap Inc.", type: "stock" },
  { symbol: "DOCS", name: "Doximity", type: "stock" },
  { symbol: "BABA", name: "Alibaba Group", type: "stock" },
  { symbol: "TCEHY", name: "Tencent Holdings (ADR)", type: "stock" },
  { symbol: "NIO", name: "Nio Inc. (ADR)", type: "stock" },
  { symbol: "SAP", name: "SAP SE (ADR)", type: "stock" },
  { symbol: "ASML", name: "ASML Holding", type: "stock" },
  { symbol: "ARM", name: "Arm Holdings", type: "stock" },
  { symbol: "AVGO", name: "Broadcom Inc.", type: "stock" },
  { symbol: "TSM", name: "Taiwan Semiconductor", type: "stock" },
  { symbol: "PYPL", name: "PayPal", type: "stock" },
  { symbol: "SHOP", name: "Shopify", type: "stock" },
  { symbol: "PINS", name: "Pinterest", type: "stock" },
  { symbol: "XYZ", name: "Block Inc.", type: "stock" },
  { symbol: "ROST", name: "Ross Stores", type: "stock" },
  { symbol: "BA", name: "Boeing", type: "stock" },
  { symbol: "CAT", name: "Caterpillar", type: "stock" },
  { symbol: "DE", name: "Deere & Co.", type: "stock" },
  { symbol: "NFLX", name: "Netflix", type: "stock" },
  { symbol: "PDD", name: "PDD Holdings", type: "stock" },
  { symbol: "MRNA", name: "Moderna", type: "stock" },
  { symbol: "LLY", name: "Eli Lilly", type: "stock" },
  { symbol: "AZN", name: "AstraZeneca", type: "stock" },
  { symbol: "BLK", name: "BlackRock", type: "stock" },
  { symbol: "GS", name: "Goldman Sachs", type: "stock" },
  { symbol: "EA", name: "Electronic Arts", type: "stock" },
  { symbol: "TTWO", name: "Take-Two Interactive", type: "stock" },
  { symbol: "SONY", name: "Sony Group Corp", type: "stock" },
  { symbol: "IDR.MC", name: "Indra Sistemas (BME)", type: "stock" },
  { symbol: "LCID", name: "Lucid Group", type: "stock" },
  { symbol: "PEP", name: "PepsiCo", type: "stock" },
  { symbol: "RBLX", name: "Roblox Corporation", type: "stock" },
  { symbol: "SE", name: "Sea Limited", type: "stock" },
  { symbol: "U", name: "Unity Software", type: "stock" },
  { symbol: "CRSR", name: "Corsair Gaming", type: "stock" },
  { symbol: "LOGI", name: "Logitech International", type: "stock" },
  { symbol: "AXP", name: "American Express", type: "stock" },
  { symbol: "KO", name: "Coca-Cola", type: "stock" },
  { symbol: "PANW", name: "Palo Alto Networks", type: "stock" },
  { symbol: "FTNT", name: "Fortinet", type: "stock" },
  { symbol: "INTU", name: "Intuit", type: "stock" },
  { symbol: "PATH", name: "UiPath Inc.", type: "stock" },
  { symbol: "AI", name: "C3.ai", type: "stock" },
  { symbol: "MDB", name: "MongoDB", type: "stock" },
  { symbol: "VERI", name: "Veritone", type: "stock" },
  { symbol: "COIN", name: "Coinbase", type: "stock" },
  { symbol: "VUAA.MI", name: "Vanguard S&P 500 UCITS ETF (Acc)", type: "stock" },
];

export const CRYPTOS = [
  { symbol: "BTC-USD", name: "Bitcoin", type: "crypto" },
  { symbol: "ETH-USD", name: "Ethereum", type: "crypto" },
  { symbol: "SOL-USD", name: "Solana", type: "crypto" },
  { symbol: "XRP-USD", name: "Ripple (XRP)", type: "crypto" },
  { symbol: "XMR-USD", name: "Monero", type: "crypto" },
  { symbol: "LTC-USD", name: "Litecoin", type: "crypto" },
  { symbol: "DOGE-USD", name: "Dogecoin", type: "crypto" },
  { symbol: "TRUMP-USD", name: "Trump Coin", type: "crypto" },
  { symbol: "SHIB-USD", name: "Shiba Inu", type: "crypto" },
  { symbol: "USDC-USD", name: "USD Coin (USDC)", type: "crypto" },
  { symbol: "XLM-USD", name: "Stellar Lumens", type: "crypto" },
  { symbol: "MINA-USD", name: "Mina Protocol", type: "crypto" },
  { symbol: "ZEC-USD", name: "Zcash", type: "crypto" },
  { symbol: "TEER-USD", name: "Integritee (TEER)", type: "crypto" },
];

export const ASSETS = [...STOCKS, ...CRYPTOS];